kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1
images:
- name: am
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/am
  newTag: 8.1.1
- name: am-custom
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/busybox
  newTag: musl
- name: amster
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/amster
  newTag: 8.0.2
- name: ds
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/ds
  newTag: 8.0.2
- name: idm
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/idm
  newTag: 8.1.1
- name: idm-custom
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/busybox
  newTag: musl
- name: ig
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/ig
  newTag: 8.0.2
- name: admin-ui
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/admin-ui
  newTag: 8.1.1
- name: end-user-ui
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/end-user-ui
  newTag: 8.0.1
- name: login-ui
  newName: image-registry.openshift-image-registry.svc:5000/png-dr-images/login-ui
  newTag: 8.0.1
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: identity-platform
namespace: pngprd