apiVersion: apps/v1
kind: Deployment

metadata:
  name: end-user-ui

spec:
  replicas: 2

  minReadySeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    spec:
      serviceAccountName: pngdr-sa

      terminationGracePeriodSeconds: 30

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/pngprd
                    operator: Exists

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: end-user-ui
                topologyKey: kubernetes.io/hostname

   

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: end-user-ui

      containers:
        - name: end-user-ui

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 500m
              memory: 1Gi